baseURL = "https://ismael.casimpan.com/quicktasks-solr"
languageCode = "en-us"
title = "Quick Tasks: Solr"
theme = "basics"

[params]
    author = "Ismael Casimpan"
    github = "icasimpan"
    #gitlab = "username2"
